In [2]:
import numpy as np

In [3]:
#https://stackoverflow.com/questions/21494489/what-does-numpy-random-seed0-do

In [4]:
import matplotlib.pyplot as plt #impot matplotlib

In [5]:
np.random.seed(0) #choosing a random seed

In [6]:
x = np.random.permutation(30)#creating a permutatuon of number up to and including 20

In [7]:
print(x)# output of array

[ 2 28 13 10 26 24 27 11 17 22  5 16  8 14 23 20  1 29  6  4 18 19  9  7
 25  3  0 21 15 12]


In [8]:
np.random.seed(0)# calling seed

In [9]:
x = np.random.permutation(30) #creating permutation 

In [10]:
print(x) # outputing array same as above due to the selected seed being called 

[ 2 28 13 10 26 24 27 11 17 22  5 16  8 14 23 20  1 29  6  4 18 19  9  7
 25  3  0 21 15 12]


In [11]:
np.random.seed(0) # calling set seed

In [12]:
y1 =  np.random.randint(50, size=4)  # creating arrat between 0-49 in a 4 size array

In [13]:
print(y1) #output array

[44 47  0  3]


In [14]:
np.random.seed(0)  # calling set seed

In [15]:
y =  np.random.randint(50, size=4) # creating array between 0-49 in a 4 size array

In [16]:
print(y) # outputing array same as above due to the selected seed being called 

[44 47  0  3]


In [18]:
np.random.seed(1)# calling another set seed

In [19]:
z =  np.random.randint(50, size=4)  # creating array between 0-49 in a 4 size array

In [20]:
print(z) #output with set seed

[37 43 12  8]


In [24]:
 np.random.seed(1) #calling set seed 1

In [25]:
z1 =  np.random.randint(50, size=4) # creating array between 0-49 in a 4 size array

In [26]:
print(z1)#output with set seed

[37 43 12  8]
